# Generated by Django 3.2.9 on 2021-12-13 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 13, 19, 49, 14, 232734))),
            ],
        ),
    ]
