# Generated by Django 3.2.9 on 2021-12-16 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211216_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='bio',
            field=models.TextField(default='bio', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 17, 6, 56, 765413)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 17, 6, 56, 765243)),
        ),
    ]
